# Generated by Django 4.2.5 on 2023-09-14 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0002_bronmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bronmodel',
            table='Bron',
        ),
    ]
