# Generated by Django 4.2.5 on 2023-09-14 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0003_stadiumsmodels_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadiumsmodels',
            name='user',
        ),
    ]
