# Generated by Django 4.2.5 on 2023-09-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0003_alter_bronmodel_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bronmodel',
            name='is_broned',
        ),
    ]
