# Generated by Django 4.2.5 on 2023-09-14 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0004_remove_bronmodel_is_broned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bronmodel',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2023, 9, 14, 16, 7, 10, 935110)),
        ),
    ]
